apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  labels:
    app: fastapi
    owner: sousa04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-app
          image: sousa04/projeto_nuvem:latest  
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://projeto:projeto@postgres:5432/projeto"
            - name: SECRET_KEY
              value: "mysecretkey" 
